# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: liquid.proto for package 'liquid'

require 'grpc'
require_relative 'liquid_pb'

module Liquid
  module LiquidParsing
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'liquid.LiquidParsing'

      rpc :ParseAndRenderString, ::Liquid::Template, ::Liquid::ParsedResult
    end

    Stub = Service.rpc_stub_class
  end
end
