// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: liquid.proto

package liquidparsingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.


const (
	LiquidParsingGrpc_ParseAndRenderString_FullMethodName = "/liquidgrpc.LiquidParsingGrpc/ParseAndRenderString"
)

// LiquidParsingGrpcClient is the client API for LiquidParsingGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiquidParsingGrpcClient interface {
	ParseAndRenderString(ctx context.Context, in *Data, opts ...grpc.CallOption) (*ParsedResult, error)
}

type liquidParsingGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewLiquidParsingGrpcClient(cc grpc.ClientConnInterface) LiquidParsingGrpcClient {
	return &liquidParsingGrpcClient{cc}
}

func (c *liquidParsingGrpcClient) ParseAndRenderString(ctx context.Context, in *Data, opts ...grpc.CallOption) (*ParsedResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParsedResult)
	err := c.cc.Invoke(ctx, LiquidParsingGrpc_ParseAndRenderString_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiquidParsingGrpcServer is the server API for LiquidParsingGrpc service.
// All implementations must embed UnimplementedLiquidParsingGrpcServer
// for forward compatibility.
type LiquidParsingGrpcServer interface {
	ParseAndRenderString(context.Context, *Data) (*ParsedResult, error)
	mustEmbedUnimplementedLiquidParsingGrpcServer()
}

// UnimplementedLiquidParsingGrpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLiquidParsingGrpcServer struct{}

func (UnimplementedLiquidParsingGrpcServer) ParseAndRenderString(context.Context, *Data) (*ParsedResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseAndRenderString not implemented")
}
func (UnimplementedLiquidParsingGrpcServer) mustEmbedUnimplementedLiquidParsingGrpcServer() {}
func (UnimplementedLiquidParsingGrpcServer) testEmbeddedByValue()                           {}

// UnsafeLiquidParsingGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiquidParsingGrpcServer will
// result in compilation errors.
type UnsafeLiquidParsingGrpcServer interface {
	mustEmbedUnimplementedLiquidParsingGrpcServer()
}

func RegisterLiquidParsingGrpcServer(s grpc.ServiceRegistrar, srv LiquidParsingGrpcServer) {
	// If the following call pancis, it indicates UnimplementedLiquidParsingGrpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LiquidParsingGrpc_ServiceDesc, srv)
}

func _LiquidParsingGrpc_ParseAndRenderString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiquidParsingGrpcServer).ParseAndRenderString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiquidParsingGrpc_ParseAndRenderString_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiquidParsingGrpcServer).ParseAndRenderString(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

// LiquidParsingGrpc_ServiceDesc is the grpc.ServiceDesc for LiquidParsingGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiquidParsingGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "liquidgrpc.LiquidParsingGrpc",
	HandlerType: (*LiquidParsingGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseAndRenderString",
			Handler:    _LiquidParsingGrpc_ParseAndRenderString_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "liquid.proto",
}
